@startuml

participant PythonSocket as "Python Socket"
participant ProgramOnPort1234 as "Program on Port 1234"

activate PythonSocket

PythonSocket -> PythonSocket: Generate Random Number (1 to 8)

PythonSocket -> ProgramOnPort1234: Send Random Number

activate ProgramOnPort1234

ProgramOnPort1234 -> ProgramOnPort1234: Receive Random Number

ProgramOnPort1234 -> PythonSocket: Acknowledge Received

deactivate ProgramOnPort1234

ProgramOnPort1234 -> ProgramOnPort1234: Reconnect and Request Data Again using reconnect()

PythonSocket -> ProgramOnPort1234: Send Random Number

activate ProgramOnPort1234

ProgramOnPort1234 -> ProgramOnPort1234: Receive Random Number

ProgramOnPort1234 -> PythonSocket: Acknowledge Received

deactivate ProgramOnPort1234

@enduml